const RoundActionTypes = {
    ADD_NEW_ROUND_START: 'ADD_NEW_ROUND_START',
    ADD_NEW_ROUND_SUCCESS: 'ADD_NEW_ROUND_SUCCESS',
    ADD_NEW_ROUND_FAILURE: 'ADD_NEW_ROUND_FAILURE',
    FETCH_ALL_ROUNDS_START: 'FETCH_ALL_ROUNDS_START',
    FETCH_ALL_ROUNDS_SUCCESS: 'FETCH_ALL_ROUNDS_SUCCESS',
    FETCH_ALL_ROUNDS_FAILURE: 'FETCH_ALL_ROUNDS_FAILURE',
    FETCH_OPEN_ROUNDS_START: 'FETCH_OPEN_ROUNDS_START',
    FETCH_OPEN_ROUNDS_SUCCESS: 'FETCH_OPEN_ROUNDS_SUCCESS',
    FETCH_OPEN_ROUNDS_FAILURE: 'FETCH_OPEN_ROUNDS_FAILURE',
  };
  
  export default RoundActionTypes;