const UserActionTypes = {
  
  FACEBOOK_SIGN_IN_START: 'FACEBOOK_SIGN_IN_START',
  GITHUB_SIGN_IN_START: 'GITHUB_SIGN_IN_START',
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  TWITTER_SIGN_IN_START: 'TWITTER_SIGN_IN_START',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',

  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
 
  FETCH_SIGN_IN_PROVIDERS_START: 'FETCH_SIGN_IN_PROVIDERS_START',
  FETCH_SIGN_IN_PROVIDERS_SUCCESS: 'FETCH_SIGN_IN_PROVIDERS_SUCCESS',
  FETCH_SIGN_IN_PROVIDERS_FAILURE: 'FETCH_SIGN_IN_PROVIDERS_FAILURE',

  CHECK_USER_SESSION: 'CHECK_USER_SESSION',

  LINK_PROVIDER_START: 'LINK_PROVIDER_START',
  LINK_PROVIDER_SUCCESS: 'LINK_PROVIDER_SUCCESS',
  LINK_PROVIDER_FAILURE: 'LINK_PROVIDER_FAILURE',

  UNLINK_PROVIDER_START: 'UNLINK_PROVIDER_START',
  UNLINK_PROVIDER_SUCCESS: 'UNLINK_PROVIDER_SUCCESS',
  UNLINK_PROVIDER_FAILURE: 'UNLINK_PROVIDER_FAILURE',
};

export default UserActionTypes;