const MatchdayActionTypes = {
  FETCH_MATCHDAY_START: "FETCH_MATCHDAY_START",
  FETCH_MATCHDAY_SUCCESS: "FETCH_MATCHDAY_SUCCESS",
  FETCH_MATCHDAY_FAILURE: "FETCH_MATCHDAY_FAILURE",
  ADD_TO_SELECTED_MATCHDAY_LIST_START: "ADD_TO_SELECTED_MATCHDAY_LIST_START",
  ADD_TO_SELECTED_MATCHDAY_LIST_SUCCESS:
    "ADD_TO_SELECTED_MATCHDAY_LIST_SUCCESS",
  ADD_TO_SELECTED_MATCHDAY_LIST_FAILURE: "ADD_TO_SELECTED_MATCHDAY_LIST_FAILURE",
  REMOVE_FROM_SELECTED_MATCHDAY_LIST: "REMOVE_FROM_SELECTED_MATCHDAY_LIST"
};

export default MatchdayActionTypes;
