const TeamActionTypes = {
    ADD_NEW_TEAM_START: 'ADD_NEW_TEAM_START',
    ADD_NEW_TEAM_SUCCESS: 'ADD_NEW_TEAM_SUCCESS',
    ADD_NEW_TEAM_FAILURE: 'ADD_NEW_TEAM_FAILURE',
    DELETE_TEAM_START: 'DELETE_TEAM_START',
    DELETE_TEAM_SUCCESS: 'DELETE_TEAM_SUCCESS',
    DELETE_TEAM_FAILURE: 'DELETE_TEAM_FAILURE',
    FETCH_ALL_TEAMS_START: 'FETCH_ALL_TEAMS_START',
    FETCH_ALL_TEAMS_SUCCESS: 'FETCH_ALL_TEAMS_SUCCESS',
    FETCH_ALL_TEAMS_FAILURE: 'FETCH_ALL_TEAMS_FAILURE',
  };
  
  export default TeamActionTypes;