const DirectoryActionTypes = {
    ADD_NEW_DIRECTORY_START: 'ADD_NEW_DIRECTORY_START',
    ADD_NEW_DIRECTORY_SUCCESS: 'ADD_NEW_DIRECTORY_SUCCESS',
    ADD_NEW_DIRECTORY_FAILURE: 'ADD_NEW_DIRECTORY_FAILURE',
    FETCH_ALL_DIRECTORY_START: 'FETCH_ALL_DIRECTORY_START',
    FETCH_ALL_DIRECTORY_SUCCESS: 'FETCH_ALL_DIRECTORY_SUCCESS',
    FETCH_ALL_DIRECTORY_FAILURE: 'FETCH_ALL_DIRECTORY_FAILURE',
  };
  
  export default DirectoryActionTypes;